services:
    databases:
        - name: chatroom
          region: eu-central-1
          type: mongo-atlas
backend:
    functions:
        - entry: app.mjs
          handler: handler
          name: express
          path: ./
          type: aws
    language:
        name: js
        packageManager: npm
    path: server
    scripts:
        deploy: npm install
        local: npm install
    environment:
        FRONTEND_URL: ${{frontend.client.subdomain}}
frontend:
    name: client
    environment:
        VITE_API_URL: ${{ backend.functions.express.url }}
    path: client
    publish: dist
    scripts:
        build: npm run build
        deploy:
            - npm install
        start:
            - npm install --silent
            - npm run dev --silent
name: chatroom-4o-with-canvas
region: eu-central-1
yamlVersion: 2
